In [2]:
import pandas as pd

# 1. Create Sample Agricultural Data
data = {
    'Region': ['North', 'South', 'North', 'East', 'South', 'North'],
    'Crop': ['Wheat', 'Corn', 'Wheat', 'Rice', 'Corn', 'Wheat'],
    'Yield_Tons': [150, 200, 170, 300, 210, 160],
    'Acres': [50, 80, 55, 100, 85, 52]
}
df = pd.DataFrame(data)
print(df)

  Region   Crop  Yield_Tons  Acres
0  North  Wheat         150     50
1  South   Corn         200     80
2  North  Wheat         170     55
3   East   Rice         300    100
4  South   Corn         210     85
5  North  Wheat         160     52

**.groupby()**

In [4]:
df.groupby(['Region','Crop'])

In [5]:
df.groupby(['Region','Crop']).sum()

              Yield_Tons  Acres
Region Crop
East   Rice          300    100
North  Wheat         480    157
South  Corn          410    165

In [7]:
df.groupby(['Yield_Tons','Acres']).sum()

                 Region   Crop
Yield_Tons Acres
150        50     North  Wheat
160        52     North  Wheat
170        55     North  Wheat
200        80     South   Corn
210        85     South   Corn
300        100     East   Rice

**AGGREGATION FUNCTIONS **

In [9]:
df.groupby('Crop')['Yield_Tons'].sum()

Crop
Corn     410
Rice     300
Wheat    480
Name: Yield_Tons, dtype: int64

In [10]:
df.groupby('Region')['Crop'].sum()

Region
East                Rice
North    WheatWheatWheat
South           CornCorn
Name: Crop, dtype: object

In [11]:
df.groupby('Crop')['Acres'].sum()

Crop
Corn     165
Rice     100
Wheat    157
Name: Acres, dtype: int64

In [12]:
df.groupby('Region').sum()

                   Crop  Yield_Tons  Acres
Region
East               Rice         300    100
North   WheatWheatWheat         480    157
South          CornCorn         410    165

In [13]:
df.groupby('Crop').sum()

                Region  Yield_Tons  Acres
Crop
Corn        SouthSouth         410    165
Rice              East         300    100
Wheat  NorthNorthNorth         480    157

In [14]:
df.groupby('Yield_Tons').sum()

           Region   Crop  Acres
Yield_Tons
150         North  Wheat     50
160         North  Wheat     52
170         North  Wheat     55
200         South   Corn     80
210         South   Corn     85
300          East   Rice    100

In [15]:
df.groupby('Acres').sum()

      Region   Crop  Yield_Tons
Acres
50     North  Wheat         150
52     North  Wheat         160
55     North  Wheat         170
80     South   Corn         200
85     South   Corn         210
100     East   Rice         300

**.mean()**

In [16]:
df.groupby('Region')['Yield_Tons'].mean()

Region
East     300.0
North    160.0
South    205.0
Name: Yield_Tons, dtype: float64

In [17]:
df.groupby('Crop')['Yield_Tons'].mean()

Crop
Corn     205.0
Rice     300.0
Wheat    160.0
Name: Yield_Tons, dtype: float64

**.count()**

In [18]:
df.groupby('Region')['Yield_Tons'].count()

Region
East     1
North    3
South    2
Name: Yield_Tons, dtype: int64

In [19]:
df.groupby('Region')['Crop'].count()

Region
East     1
North    3
South    2
Name: Crop, dtype: int64

In [20]:
df.groupby('Region')['Acres'].count()

Region
East     1
North    3
South    2
Name: Acres, dtype: int64