In [16]:
import pandas as pd

data={
    'Department':['HR','Sales','IT','Sales','IT','HR','Sales'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[50000,60000,45000,48000,70000,72000,71000],
    'Experience':[2,4,3,5,6,7,5]
}

df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

**.groupby()**

In [3]:
df1=df.groupby(['Department','Experience'])
print(df1)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7a04be917e90>

**.sum()**

In [4]:
df1=df.groupby(['Department','Experience']).sum()
print(df1)

                      Employees  Salary
Department Experience
HR         2                  A   50000
           7                  F   72000
IT         3                  C   45000
           6                  E   70000
Sales      4                  B   60000
           5                 DG  119000

In [5]:
df2=df.groupby('Experience').sum()
print(df2)

            Department Employees  Salary
Experience
2                   HR         A   50000
3                   IT         C   45000
4                Sales         B   60000
5           SalesSales        DG  119000
6                   IT         E   70000
7                   HR         F   72000

**AGGREGATION FUNCTIONS **

In [6]:
df.groupby('Department')['Salary'].sum()

Department
HR       122000
IT       115000
Sales    179000
Name: Salary, dtype: int64

In [8]:
df.groupby('Department').sum()

           Employees  Salary  Experience
Department
HR                AF  122000           9
IT                CE  115000           9
Sales            BDG  179000          14

In [9]:
df.groupby('Salary')['Department'].sum()

Salary
45000       IT
48000    Sales
50000       HR
60000    Sales
70000       IT
71000    Sales
72000       HR
Name: Department, dtype: object

**.mean()**

In [10]:
df.groupby('Department')['Salary'].mean()

Department
HR       61000.000000
IT       57500.000000
Sales    59666.666667
Name: Salary, dtype: float64

**.count()**

In [17]:
df.groupby('Department')['Employee'].count()

Department
HR       2
IT       2
Sales    3
Name: Employee, dtype: int64

**MULTIPLE AGGREGATIONS **

In [18]:
df.groupby("Department")["Salary"].agg(['sum','mean','std'])

               sum          mean           std
Department
HR          122000  61000.000000  15556.349186
IT          115000  57500.000000  17677.669530
Sales       179000  59666.666667  11503.622618

**CUSTOM AGGREGATIONS **

In [21]:
df.groupby('Department').agg({
    "Salary":'sum', 'Experience':'mean'
})

            Salary  Experience
Department
HR          122000    4.500000
IT          115000    4.500000
Sales       179000    4.666667

**BROADCAST GROUP MEAN TO EACH ROW**

In [29]:
df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')
print(df['Dept_Avg_Salary'])

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Dept_Avg_Salary, dtype: float64

In [30]:
df['Dept_Avg_Salary'] = df.groupby('Department')['Salary'].transform('mean')
df4=df['Dept_Avg_Salary']
print(df4)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Dept_Avg_Salary, dtype: float64

**FILTERING GROUPS **

In [32]:
df.groupby('Department').filter(lambda x : len(x)>2)

  Department Employee  Salary  Experience  Dept_Avg_Salary
1      Sales        B   60000           4     59666.666667
3      Sales        D   48000           5     59666.666667
6      Sales        G   71000           5     59666.666667

In [33]:
df5=df.groupby('Department').filter(lambda x : len(x)>2)
print(df5)

  Department Employee  Salary  Experience  Dept_Avg_Salary
1      Sales        B   60000           4     59666.666667
3      Sales        D   48000           5     59666.666667
6      Sales        G   71000           5     59666.666667

**PIVOT TABLES **

In [35]:
#Mean salary by dept and experience

df.pivot_table(
    values='Salary',
    index='Department',
    columns='Experience',
    aggfunc='mean'
)

Experience        2        3        4        5        6        7
Department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
Sales           NaN      NaN  60000.0  59500.0      NaN      NaN