In [18]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

In [17]:
df.isnull()   # False --->Value is not missing # Trie ---> Value is missing

    Name    Age  Gender  Salary
0  False  False   False   False
1  False  False   False    True
2  False  False    True    True
3  False   True   False   False
4  False  False   False   False

In [7]:
df.isnull()  # Interactive table

    Name    Age  Gender  Salary
0  False  False   False   False
1  False  False   False    True
2  False  False    True   False
3  False   True   False   False
4  False  False   False   False

In [8]:
df.isna()    # same as isnull()

    Name    Age  Gender  Salary
0  False  False   False   False
1  False  False   False    True
2  False  False    True   False
3  False   True   False   False
4  False  False   False   False

In [19]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, None , 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)


df.isna().sum()     # Counts how many missing values are tehre in each column

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None      NaN
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

Name      0
Age       1
Gender    1
Salary    2
dtype: int64

In [23]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, None, 40000, 60000]
}
df = pd.DataFrame(data)

df.isna().sum().sum()   # Counts Total Missing Values

np.int64(4)

In [24]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)

df.isna().sum().sum()

np.int64(3)

In [27]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna()   # It drops the rows with any NaN and prints only the contents in a tabel with no NaN Values

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F      NaN

    Name   Age Gender   Salary
0  Alice  25.0      F  50000.0

In [30]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, None]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna()

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F      NaN

    Name   Age Gender   Salary
0  Alice  25.0      F  50000.0

In [32]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [None, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, None]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna()

Original DataFrame:
      Name   Age Gender   Salary
0    Alice   NaN      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F      NaN

Empty DataFrame
Columns: [Name, Age, Gender, Salary]
Index: []

In [33]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna(axis=1)  # Drops any cpulumns with any NaN values

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

In [34]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, 45, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
df.dropna(axis=1)

Original DataFrame:
      Name  Age Gender   Salary
0    Alice   25      F  50000.0
1      Bob   31      M      NaN
2  Charlie   22   None  30000.0
3    David   45      M  40000.0
4      Eva   27      F  60000.0

      Name  Age
0    Alice   25
1      Bob   31
2  Charlie   22
3    David   45
4      Eva   27

In [35]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna(how='all')  # Drops rows where all the values are NaN

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

In [42]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', None, 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan,None, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna(how='all')  # Drop rows where all values are NaN

Original DataFrame:
    Name   Age Gender   Salary
0  Alice  25.0      F  50000.0
1    Bob  31.0      M      NaN
2   None  22.0   None      NaN
3  David   NaN      M  40000.0
4    Eva  27.0      F  60000.0

    Name   Age Gender   Salary
0  Alice  25.0      F  50000.0
1    Bob  31.0      M      NaN
2   None  22.0   None      NaN
3  David   NaN      M  40000.0
4    Eva  27.0      F  60000.0

In [10]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna(subset=['Gender'])
df.dropna(thresh=3)

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

In [11]:
df.dropna(thresh=3)

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

In [15]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, None, None, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.dropna(subset=['Age'])
df.dropna(thresh=3)

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob   NaN      M      NaN
2  Charlie   NaN   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

    Name   Age Gender   Salary
0  Alice  25.0      F  50000.0
3  David   NaN      M  40000.0
4    Eva  27.0      F  60000.0

FILLING MISSING VALUES

In [18]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)

df.fillna(0)  # Fills all the missing values with the value mentioned in the bracket

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      0.0
2  Charlie  22.0      0  30000.0
3    David   0.0      M  40000.0
4      Eva  27.0      F  60000.0

In [22]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, None, None, 27],
    'Gender': ['F', np.nan, None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, None, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.fillna({'Age':"Unknown",'Gender':"Not mentioned","Salary":"Not specified"})

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0    NaN      NaN
2  Charlie   NaN   None  30000.0
3    David   NaN      M      NaN
4      Eva  27.0      F  60000.0

      Name      Age         Gender         Salary
0    Alice     25.0              F        50000.0
1      Bob     31.0  Not mentioned  Not specified
2  Charlie  Unknown  Not mentioned        30000.0
3    David  Unknown              M  Not specified
4      Eva     27.0              F        60000.0

In [25]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)

df.ffill()

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M  50000.0
2  Charlie  22.0      M  30000.0
3    David  22.0      M  40000.0
4      Eva  27.0      F  60000.0

In [26]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.bfill()

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M  30000.0
2  Charlie  22.0      M  30000.0
3    David  27.0      M  40000.0
4      Eva  27.0      F  60000.0

In [28]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.interpolate()    # It fills the missing values in ascending or decsenidng order according to the previous and after values

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

/tmp/ipython-input-3906940085.py:14: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()    # It fills the missing values in ascending or decsenidng order according to the previous and after values

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M  40000.0
2  Charlie  22.0   None  30000.0
3    David  24.5      M  40000.0
4      Eva  27.0      F  60000.0

REPLACING VALUES

In [30]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

print("\n === NEW DATA FRAME ==  ")
df.replace('Eva','Emily')

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

 === NEW DATA FRAME ==

      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4    Emily  27.0      F  60000.0

In [33]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 31, 22, None, 27],
    'Gender': ['F', 'M', None, 'M', 'F'],
    'Salary': [50000, np.nan, 30000, 40000, 60000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

print("\n === NEW DATA FRAME ==  ")
df.replace(['Eva','F'],['Ethan','M'])

Original DataFrame:
      Name   Age Gender   Salary
0    Alice  25.0      F  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4      Eva  27.0      F  60000.0

 === NEW DATA FRAME ==

      Name   Age Gender   Salary
0    Alice  25.0      M  50000.0
1      Bob  31.0      M      NaN
2  Charlie  22.0   None  30000.0
3    David   NaN      M  40000.0
4    Ethan  27.0      M  60000.0